version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: log_management_db
    environment:
      POSTGRES_DB: log_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/config/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d log_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 